### PR TITLE
Support encrypting with private key

### PR DESCRIPTION
**Pull request by hkizuna**
This pr add new functions that encrypt with private key and decrypt with public key. Some api providers required these as part of their signature algorithm (in my case). They are using this subtle implementation detail of RSA to improve security.

### CODE REVIEW

**Comment by sybrenstuvel** [comment]
Where are these features used?

**Comment by hkizuna** [comment]
In my case, it's [JDPay](http://payapi.jd.com/) provided by jd.com. I cant find any english api service used this feature, but there is a php counterpart [openssl_private_encrypt](http://php.net/manual/en/function.openssl-private-encrypt.php).

**Comment by sybrenstuvel** [comment]
So what is exactly the difference between your new code and the existing code for signing and verification of signatures?

**Comment by hkizuna** [comment]
My new code is just application of private key operations of [encryption process](https://tools.ietf.org/html/rfc2313#section-8). In my case, it is used as an incomplete [signature algorithm](https://tools.ietf.org/html/rfc2313#section-10) that without message digesting and data encoding steps.

**Comment by sybrenstuvel** [comment]
I don't quite agree with the implementation. According to [RFC 8017 section 7.2. RSAES-PKCS1-v1_5](https://tools.ietf.org/html/rfc8017#page-28) there is no "encryption with private key". Calling it "encryption" also doesn't make sense when the entire world can decrypt the result.

I would suggest adding an entry `{'DUMMY': b''}` value to the `HASH_ASN1` dict, which can then be passed to the `sign_hash()` function. That way the semantics of the words "encrypt" and "sign" aren't muddled.

Note that there is an issue in this approach: `_find_method_hash()` won't handle this `DUMMY` entry properly, as any byte string starts with `b''`. It should skip the `DUMMY` entry, so that unknown hash methods are rejected (rather than assumed to be `DUMMY`). `verify()` could then maybe have a `hash_method=''` parameter that prevents `_find_method_hash()` to be called when it's not an empty string? At least place ample warnings in the documentation about this, because it's bound to create some security hole when used improperly.

**Comment by sybrenstuvel** [comment]
Closing this PR due to the inactivity of the original author.

**Pull request closed without merging**
