### PR TITLE
Remove old version excluded files from CodeClimate

### PR DESCRIPTION
**Pull request by adamantike**
Just a remaining clean for ```4.0```.

### CODE REVIEW

**Comment by sybrenstuvel** [comment]
Instant accept :) Merged in 5acf9cdde2a5b93c9603619eedd3ed184e53d444

**Comment by adamantike** [comment]
Now you can accept PRs and get commits [**automatically squashed**](https://github.com/blog/2141-squash-your-commits) on master, keeping a clean git history! :D

**Comment by sybrenstuvel** [comment]
That looks useful, I'll have to give that a try some time to see whether it actually does what I want (rebase onto master and then a ff-only merge, with squashing optional).

**Comment by adamantike** [comment]
According to [docs](https://help.github.com/articles/about-pull-request-merge-squashing/), that's the current behaviour! But it seems squashing is **not** optional... However, still useful for 1-commit PRs.

**Pull request closed without merging**
