### PR TITLE
Add py.typed marker file for PEP 561 compliance

### PR DESCRIPTION
**Pull request by and-semakin**
The code in master branch is type annotated now but type checkers (for example mypy) will not be able to use this annotations when checking users code which imports `rsa` library. To fix this the package should be [PEP-561](https://www.python.org/dev/peps/pep-0561/) compliant.

In this PR the file needed to make package working with type checkers properly was added.

Example:
```python
import rsa

(pubkey, privkey) = rsa.newkeys(512)
```

Without `py.typed`:
```
$ mypy example.py 
example.py:1: error: No library stub file for module 'rsa'
example.py:1: note: (Stub files are from https://github.com/python/typeshed)
```

With `py.typed`:
```
$ mypy example.py
Success: no issues found in 1 source file
```

### CODE REVIEW

**Comment by sybrenstuvel** [comment]
Thanks, I'm all for better type checking support, and I didn't know about this PEP. Can you also add a line to the `CHANGELOG.md` file that explains this? Then I'll merge the PR.

**Comment by and-semakin** [comment]
Updated `CHANGELOG.md` :)

**Comment by and-semakin** [comment]
@sybrenstuvel please let me know if there is something I need to fix or improve.

**Comment by sybrenstuvel** [comment]
It's good as-is, I'll move the changelog lines to the appropriate spot when I merge the PR. It's mostly a matter of me having time ;-)

**Comment by sybrenstuvel** [comment]
Sorry for taking so long! It's been merged as d1de4c8be04027cee0586566576f74cc3f883a9b and will be in the next release.

**Pull request closed without merging**
