### PR TITLE
Drop support for EOL Python 3.3

### PR DESCRIPTION
**Pull request by hugovk**
As suggested by the [README](https://github.com/sybrenstuvel/python-rsa#plans-for-the-future):

> Version 4.0 will drop support for Python 2.6, and possibly for Python 3.3.

Here's the pip installs for Python-RSA from PyPI for the last month, showing virtually no downloads for 3.3:
```
$ pypinfo --percent --pip rsa pyversion
python_version percent download_count
-------------- ------- --------------
2.7              93.9%     10,098,358
3.5               2.3%        247,119
3.6               1.6%        166,804
2.6               1.5%        161,954
3.4               0.8%         83,405
3.3               0.0%            885
3.7               0.0%            408
3.2               0.0%              5
None              0.0%              4
3.1               0.0%              1

```

### CODE REVIEW

**Comment by hugovk** [comment]
Rebased on master to remove merge conflict and CI now passes.

**Comment by hugovk** [comment]
@sybrenstuvel Hello, any thoughts on this PR? Thank you!

**Comment by sybrenstuvel** [comment]
I think it's a good idea, will merge it soon-ish. Thanks for the PR.

**Comment by hugovk** [comment]
Just to let you know, pytest has dropped 2.6 and 3.3 so master is failing:

https://travis-ci.org/hugovk/python-rsa/builds/308944678

**Comment by sybrenstuvel** [comment]
Thanks again for the PR. Time we let go of the ancient ;-)

**Pull request merged**
