### PR TITLE
Drop support for Python 3.6

### PR DESCRIPTION
**Pull request by ziegenberg**
Python 3.6 EOLed 11 months ago.

### CODE REVIEW

**Comment by myheroyuki** [comment]
Thanks, this looks like a good contribution! Can you update the docs (specifically, `installation.rst`) to reflect this PR?

**Comment by ziegenberg** [comment]
Hi! I'll update the docs as soon as my workstation is back in a usable state. That should be in the coming week.

**Comment by ziegenberg** [comment]
I amended my commit and updated `installation.rst` as requested.

**Comment by sybrenstuvel** [comment]
Thanks for the PR!

**Pull request merged**
